s390x.S: fix errors related to stack backtraces
caml_raise_exception: set caml_backtrace_pos = 0, this is not a reraise

caml_ml_array_bound_error: save SP before decrementing it, otherwise
it doesn't match the frame descriptor generated by ocamlopt

Cleanup: no need to set caml_return_address to 0 on return, that was
useful a long time ago but no longer is.